#!/bin/bash

cd "$(dirname "$0")"

if [[ "$VIRTUAL_ENV" = "" ]]
then
    if [ -d "venv" ]
    then
        source venv/bin/activate
    else
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    fi
fi

python ./main.py "$@"
